//SEARCHBAR START
let search = document.getElementById('search');
let search_icon = document.getElementById('search_icon');

search_icon.addEventListener('click', () => {
    search.classList.toggle('search_input');
})

let cato_bx = document.getElementById('cato_bx');
let left_scroll = document.getElementById('left_scroll');
let right_scroll = document.getElementById('right_scroll');

left_scroll.addEventListener('click', () => {
    cato_bx.scrollLeft -= 100;
})
right_scroll.addEventListener('click', () => {
    cato_bx.scrollLeft += 100;
})
// Movies Box Set

const movies = [{
            id: 36,
            img: "mimg/the gazi attck.jpg",
            down_img: "img/the-ghazi-attack-poster.webp",
            title: "The Gazi Attack",
            letter: "t",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "none",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 9.9,
            url: "the_gazi_attack.html",
            tppr: "trend",
            msot: "movie",
            screen1: "img/gazi1.jpg",
            screen2: "img/gazi2.jpg",
            screen3: "img/gazi3.jpg",
            ph420: "img/the-ghazi-attack-poster.webp",
            ph720: "mimg/comndo.jpg",
            ph1080: "img/the-ghazi-attack-poster.webp",
        },
        {
            id: 35,
            img: "mimg/comndo.jpg",
            title: "Comndo",
            letter: "c",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "none",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 9.3,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },

        // img: "mimg/caption phillips.jpg",
        // title: "Caption Phillips",

        {
            id: 34,
            img: "mimg/6under.jpg",
            title: "Nguyễn Thanh Sơn",
            letter: "n",
            // genre1: "action",
            // genre2: "Cửa",
            // genre3: "none",
            // genre4: "biography",
            // genre5: "animation",
            // genre6: "none",
            // genre7: "documentary",
            // genre8: "none",
            // genre9: "18+",
            // genre10: "scifi",
            // genre11: "horor",
            year:2023,
            // rate: 9.1,
            url: "https://www.24h.com.vn/",
            // tppr: "trend",
            // msot: "movie"
        },
        {
            id: 33,
            img: "mimg/bloodshoot.jpg",
            title: "Blood Shoot",
            letter: "b",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "none",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 9.7,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 32,
            img: "mimg/blade.jpg",
            title: "Blade",
            letter: "b",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "none",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 7.7,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 31,
            img: "mimg/takepoint.webp",
            title: "Take Point",
            letter: "t",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "none",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 7.9,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 30,
            img: "mimg/battel drown.jpg",
            title: "Battel Drown",
            letter: "b",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 8.9,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 29,
            img: "mimg/bagi.jpg",
            title: "Bagi",
            letter: "b",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 8.8,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 28,
            img: "mimg/bad boys.jpg",
            title: "Bad Boys",
            letter: "b",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 6.8,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 27,
            img: "mimg/ateet.jpg",
            title: "Ateet",
            letter: "a",
            genre1: "action",
            genre2: "none",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 9.7,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 26,
            img: "mimg/aqwaman.jpg",
            title: "Aqwaman",
            letter: "a",
            genre1: "action",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 9.6,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 25,
            img: "mimg/angel.jpg",
            title: "Angel",
            letter: "a",
            genre1: "action",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 8.8,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 24,
            img: "mimg/allahdin.jpg",
            title: "Allahdin",
            letter: "a",
            genre1: "action",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 8.2,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 23,
            img: "mimg/air.jpg",
            title: "Air",
            letter: "a",
            genre1: "none",
            genre2: "crime",
            genre3: "none",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 9.1,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 22,
            img: "mimg/acceleration.jpg",
            title: "Acceler ration",
            letter: "a",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 9.9,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 21,
            img: "mimg/abcd.jpg",
            title: "ABCD",
            letter: "a",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 7.9,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 20,
            img: "mimg/a perfact.jpg",
            title: "A Pefact",
            letter: "a",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 6.9,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 19,
            img: "mimg/6under.jpg",
            title: "6 Underground",
            letter: "u",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 9.2,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 18,
            img: "mimg/noah.webp",
            title: "Noah",
            letter: "n",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 8.2,
            url: "themanor.html",
            tppr: "popular",
            msot: "movie"
        },
        {
            id: 17,
            img: "mimg/notimethedie.webp",
            title: "No Time The Die",
            letter: "n",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 8.5,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie",
            upload: "latest"
        },
        {
            id: 16,
            img: "mimg/oz.webp",
            title: "OZ",
            letter: "o",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 8.6,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 15,
            img: "mimg/paul.webp",
            title: "Paul",
            letter: "p",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 9.3,
            url: "themanor.html",
            tppr: "recent",
            msot: "movie",
            upload: "latest"
        },
        {
            id: 14,
            img: "mimg/pixels.webp",
            title: "Pixels",
            letter: "p",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 7.3,
            url: "themanor.html",
            tppr: "popluar",
            msot: "movie"
        },
        {
            id: 13,
            img: "mimg/Qismat_2.webp",
            title: "Qismat 2",
            letter: "q",
            genre1: "none",
            genre2: "crime",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "none",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 5.8,
            url: "themanor.html",
            tppr: "recent",
            msot: "movie",
            upload: "latest"
        },
        {
            id: 12,
            img: "mimg/red_notice.jpg",
            title: "Red Notice",
            letter: "r",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 6.8,
            url: "themanor.html",
            tppr: "recent",
            msot: "movie"
        },
        {
            id: 11,
            img: "mimg/shershaah.webp",
            title: "Shershaah",
            letter: "s",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 7.8,
            url: "themanor.html",
            tppr: "recent",
            msot: "series",
            upload: "latest"
        },
        {
            id: 10,
            img: "mimg/shiddat.webp",
            title: "Shiddat",
            letter: "s",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 8.8,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie"
        },
        {
            id: 9,
            img: "mimg/snakeeyes.webp",
            title: "Snake Eyes",
            letter: "s",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 8.9,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie",
            upload: "latest"
        },
        {
            id: 8,
            img: "mimg/takepoint.webp",
            title: "Take Point",
            letter: "t",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 9.8,
            url: "themanor.html",
            tppr: "popular",
            msot: "movie"
        },
        {
            id: 7,
            img: "mimg/The-Manor.webp",
            title: "The Manor",
            letter: "t",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 8.8,
            url: "themanor.html",
            tppr: "trend",
            msot: "movie",
            upload: "latest"
        },
        {
            id: 6,
            img: "mimg/theblackwater.webp",
            title: "The Black Water",
            letter: "t",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 8.8,
            url: "theblackwater.html",
            tppr: "recent",
            msot: "series"
        },
        {
            id: 5,
            img: "mimg/theoutpost.webp",
            title: "The Out Post",
            letter: "t",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2019,
            rate: 5.8,
            url: "venom2.html",
            tppr: "recent",
            msot: "series",
            upload: "latest"
        },
        {
            id: 4,
            img: "mimg/thevault.webp",
            title: "The Vault",
            letter: "t",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2019,
            rate: 5.8,
            url: "venom2.html",
            tppr: "popular",
            msot: "movie"
        },
        {
            id: 3,
            img: "mimg/venom2.webp",
            title: "Venom 2",
            letter: "v",
            genre1: "none",
            genre2: "",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2021,
            rate: 9.2,
            url: "venom2.html",
            tppr: "trend",
            msot: "movie",
            upload: "latest"
        },
        {
            id: 2,
            img: "mimg/Warrior.webp",
            title: "Warrior",
            letter: "w",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2020,
            rate: 8.6,
            url: "bfg.html",
            tppr: "popular",
            msot: "movie"
        },
        {
            id: 1,
            img: "mimg/xtreme.webp",
            title: "Xtreme",
            letter: "x",
            genre1: "none",
            genre2: "none",
            genre3: "adeventure",
            genre4: "biography",
            genre5: "animation",
            genre6: "comady",
            genre7: "documentary",
            genre8: "drama",
            genre9: "18+",
            genre10: "scifi",
            genre11: "horor",
            year: 2022,
            rate: 6.5,
            url: "bfg.html",
            tppr: "recent",
            msot: "movie",
            upload: "latest"
        },
    ]
    // all array copyed!

// SEARCH 3 JS
let search_bx2 = document.getElementsByClassName('search_bx2')[0];

// SEARCH 2 JS
window.addEventListener('load', () => {
    movies.forEach(element => {
        const { img, title, year, url } = element;

        let card = document.createElement('a');
        card.href = url;
        card.innerHTML = ` <img src="${img}" alt="">
        <div class="content2">
            <h6>${title}</h6>
            <p>${year}</p>
        </div>`;
        search_bx2.appendChild(card);
    });
});

// SEARCH 1 JS
search.addEventListener('keyup', () => {
    let filter = search.value.toUpperCase();
    let a = search_bx2.getElementsByTagName('a');
    for (let i = 0; i < a.length; i++) {
        let b = a[i].getElementsByClassName('content2')[0];
        let c = b.getElementsByTagName('h6')[0];

        let TextValue = c.textContent || c.innerText;
        if (TextValue.toUpperCase().indexOf(filter) > -1) {
            a[i].style.display = '';
            search_bx2.style.visibility = "visible";
            search_bx2.style.opacity = 1;
        } else {
            a[i].style.display = 'none';
        }
        if (search.value == 0) {
            search_bx2.style.visibility = "hidden";
            search_bx2.style.opacity = 0;
        }
    }
})
//SEARCHBAR END